CinemaSystem/Models/MovieSession.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CinemaSystem.Models
{

    // 1 numaralı salonda yer alan filmin seansları burada bulunuyor
    public class MovieSession
    {
        public int Id { get; set; }

        public int CinemaTheaterMovieId { get; set; }
        public CinemaTheaterMovie CinemaTheaterMovie { get; set; }

        public DateTime StartedDate { get; set; } 
        public DateTime FinishedDate { get; set; }
    }
}

CinemaSystem/Models/TheaterChair.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CinemaSystem.Models
{
    public class TheaterChair
    {
        public int Id { get; set; }

        public int CinemaTheaterId { get; set; }
        public CinemaTheater CinemaTheater { get; set; }
        
        public string ChairCode { get; set; }
    }
}

CinemaSystem/Controllers/MovieSessionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CinemaSystem.Data;
using CinemaSystem.Models;
using Microsoft.AspNetCore.Authorization;

namespace CinemaSystem.Controllers
{
    public class MovieSessionsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MovieSessionsController(ApplicationDbContext context)
        {
            _context = context;
        }

        [Authorize(Roles = "Admin")]
        // GET: MovieSessions
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.MovieSessions.Include(m => m.CinemaTheaterMovie);
            return View(await applicationDbContext.ToListAsync());
        }

        [Authorize(Roles = "Admin")]
        // GET: MovieSessions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movieSession = await _context.MovieSessions
                .Include(m => m.CinemaTheaterMovie)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movieSession == null)
            {
                return NotFound();
            }

            return View(movieSession);
        }

        [Authorize(Roles = "Admin")]
        // GET: MovieSessions/Create
        public IActionResult Create()
        {
            ViewData["CinemaTheaterMovieId"] = new SelectList(_context.CinemaTheaterMovies, "Id", "Id");
            return View();
        }

        // POST: MovieSessions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CinemaTheaterMovieId,StartedDate,FinishedDate")] MovieSession movieSession)
        {
            if (ModelState.IsValid)
            {
                _context.Add(movieSession);
                await _context.SaveChangesAsync();
                return RedirectToAction("MovieSessionList", "Admin");
            }
            ViewData["CinemaTheaterMovieId"] = new SelectList(_context.CinemaTheaterMovies, "Id", "Id", movieSession.CinemaTheaterMovieId);
            return RedirectToAction("MovieSessionList", "Admin");
        }

        [Authorize(Roles = "Admin")]
        // GET: MovieSessions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movieSession = await _context.MovieSessions.FindAsync(id);
            if (movieSession == null)
            {
                return NotFound();
            }
            ViewData["CinemaTheaterMovieId"] = new SelectList(_context.CinemaTheaterMovies, "Id", "Id", movieSession.CinemaTheaterMovieId);
            return View(movieSession);
        }

        // POST: MovieSessions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CinemaTheaterMovieId,StartedDate,FinishedDate")] MovieSession movieSession)
        {
            if (id != movieSession.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(movieSession);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MovieSessionExists(movieSession.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("MovieSessionList", "Admin");
            }
            ViewData["CinemaTheaterMovieId"] = new SelectList(_context.CinemaTheaterMovies, "Id", "Id", movieSession.CinemaTheaterMovieId);
            return RedirectToAction("MovieSessionList", "Admin");
        }


        [Authorize(Roles = "Admin")]
        // GET: MovieSessions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movieSession = await _context.MovieSessions
                .Include(m => m.CinemaTheaterMovie)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movieSession == null)
            {
                return NotFound();
            }

            return View(movieSession);
        }

        // POST: MovieSessions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var movieSession = await _context.MovieSessions.FindAsync(id);
            _context.MovieSessions.Remove(movieSession);
            await _context.SaveChangesAsync();
            return RedirectToAction("MovieSessionList", "Admin");
        }

        private bool MovieSessionExists(int id)
        {
            return _context.MovieSessions.Any(e => e.Id == id);
        }
    }
}

CinemaSystem/Controllers/MovieTheatersPageController.cs
using CinemaSystem.Data;
using CinemaSystem.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Localization;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace CinemaSystem.Controllers
{
    public class MovieTheatersPageController : Controller
    {

        private readonly ApplicationDbContext _context;

        private readonly IStringLocalizer<MovieTheatersPageController> _localizer;

        public MovieTheatersPageController(ApplicationDbContext context, IStringLocalizer<MovieTheatersPageController> localizer)
        {
            _context = context;
            _localizer = localizer;
        }
        [Authorize]
        public async Task<IActionResult> Index(int? id,string culture)
        {
            if (id == null)
            {
                return NotFound();
            }
            var rqf = Request.HttpContext.Features.Get<IRequestCultureFeature>();
            // Culture contains the information of the requested culture


            if (culture != null)
            {
                var cultureInfo = new System.Globalization.CultureInfo(culture);
                Thread.CurrentThread.CurrentCulture = cultureInfo;
            }
            var selectedCulture = rqf.RequestCulture.Culture;

            ViewData["ctr"] = selectedCulture;

            ViewData["ContactUs"] = _localizer["ContactUs"];
            ViewData["MenuContact"] = _localizer["MenuContact"];
            ViewData["MenuHome"] = _localizer["MenuHome"];
            ViewData["MenuProfile"] = _localizer["MenuProfile"];
            ViewData["MenuVisions"] = _localizer["MenuVisions"];
            ViewData["PageFirstTitle"] = _localizer["PageFirstTitle"];
            ViewData["PagePromotionCode"] = _localizer["PagePromotionCode"];
            ViewData["TheaterNo"] = _localizer["TheaterNo"];

            ViewBag.movieIdForGetSession=id;



            var cinemaTheatersByMovieId = _context.CinemaTheaterMovies.Include(c => c.CinemaTheater).Include(c => c.Movie);
            ViewBag.id = id;
            ViewBag.ctbymi = await cinemaTheatersByMovieId.Where(x=>x.MovieId==id && x.FinishedDate>DateTime.Now.Date).ToListAsync();
            return View();
        }
        [Authorize]
        public async Task<IActionResult> MovieSessions(int? id,string? movieId,string culture)
        {
            if (id == null)
            {
                return NotFound();
            }
            var rqf = Request.HttpContext.Features.Get<IRequestCultureFeature>();
            // Culture contains the information of the requested culture


            if (culture != null)
            {
                var cultureInfo = new System.Globalization.CultureInfo(culture);
                Thread.CurrentThread.CurrentCulture = cultureInfo;
            }
            var selectedCulture = rqf.RequestCulture.Culture;

            ViewData["ctr"] = selectedCulture;

            ViewData["ContactUs"] = _localizer["ContactUs"];
            ViewData["MenuContact"] = _localizer["MenuContact"];
            ViewData["MenuHome"] = _localizer["MenuHome"];
            ViewData["MenuProfile"] = _localizer["MenuProfile"];
            ViewData["MenuVisions"] = _localizer["MenuVisions"];
            ViewData["PageFirstTitle"] = _localizer["PageFirstTitle"];
            ViewData["PagePromotionCode"] = _localizer["PagePromotionCode"];
            ViewData["MovieSessionPageFirstTitle"] = _localizer["MovieSessionPageFirstTitle"];
            ViewData["MovieSessionPageButton"] = _localizer["MovieSessionPageButton"];



            //MOVİE ID YE GÖRE DE KONTROL OLACAK
            // 
            

            var movieSessionsByMovieTheaterId = _context.MovieSessions.Include(c => c.CinemaTheaterMovie);
            ViewBag.msbyti = await movieSessionsByMovieTheaterId.Where(x=>x.CinemaTheaterMovieId==id && x.FinishedDate>=DateTime.Now && x.CinemaTheaterMovie.MovieId.ToString()==movieId).ToListAsync();
            return View();

        }
        [Authorize]
        public async Task<IActionResult> TheaterChairs(int? id,string culture)
        {
            if (id == null)
            {
                return NotFound();
            }
            var rqf = Request.HttpContext.Features.Get<IRequestCultureFeature>();
            // Culture contains the information of the requested culture


            if (culture != null)
            {
                var cultureInfo = new System.Globalization.CultureInfo(culture);
                Thread.CurrentThread.CurrentCulture = cultureInfo;
            }
            var selectedCulture = rqf.RequestCulture.Culture;

            ViewData["ctr"] = selectedCulture;

            ViewData["ContactUs"] = _localizer["ContactUs"];
            ViewData["MenuContact"] = _localizer["MenuContact"];
            ViewData["MenuHome"] = _localizer["MenuHome"];
            ViewData["MenuProfile"] = _localizer["MenuProfile"];
            ViewData["MenuVisions"] = _localizer["MenuVisions"];
            ViewData["PageFirstTitle"] = _localizer["PageFirstTitle"];
            ViewData["PagePromotionCode"] = _localizer["PagePromotionCode"];
            ViewData["TheaterChairsPageChairNo"] = _localizer["TheaterChairsPageChairNo"];
            ViewData["TheaterChairsPageCreateButton"] = _localizer["TheaterChairsPageCreateButton"];


            var movieSessions = _context.MovieSessions.Include(c => c.CinemaTheaterMovie);
            var cinemaMovieSession = await movieSessions.SingleOrDefaultAsync(x => x.Id == id);

            var theaterChairs = await _context.TheaterChairs.Include(c => c.CinemaTheater)
                .Where(x=>x.CinemaTheaterId==cinemaMovieSession.CinemaTheaterMovie.CinemaTheaterId).ToListAsync();

            ViewBag.movieSessionId = id;
            ViewBag.theaterChairs = theaterChairs;

            var movieTickets = await _context.MovieTickets.Include(c => c.MovieSession).Include(c => c.TheaterChair)
                .Where(x => x.MovieSessionId == id).ToListAsync();

            var movieTicketsChair=new List<int>();

            foreach (var item in movieTickets)
            {
                movieTicketsChair.Add(item.TheaterChairId);
            }


            ViewBag.movieTicketsChair = movieTicketsChair;

            //biletleri listele bu seansa olan 
            // biletlerin içerdiği koltukları kırmızı yap gerisi alınabilsin.
         
            return View();


        }
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateTicket([Bind("Id,MovieSessionId,BuyDate,Price,Number,UserId,TheaterChairId")] MovieTicket movieTicket)
        {

            if(ModelState.IsValid)
            {
                _context.Add(movieTicket);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Visions");
            }

            return RedirectToAction("Index", "Visions");
            //Movie session id 
            //Koltuk id -> select den seçtir


        }
    }
}

CinemaSystem/Views/MovieTheatersPage/Index.cshtml
@{ ViewData["Title"] = "Index";
    Layout = "_DefaultLayout";}

<h1>@ViewBag.id</h1>

<br />
<br />

<div class="container">
    <h1 class="text-center">@ViewData["PageFirstTitle"]</h1>
    <br />
    <div class="row" style="display:flex; justify-content:center; flex-wrap:wrap;">

        @foreach (var item in ViewBag.ctbymi)
        {
            <div class="col-md-4 text-center" style="border:5px solid black; margin-left:15px; margin-top:5px; padding-bottom:15px; padding-top:15px;">
                <div class="card">
                    <h1 class="card-header">@ViewData["TheaterNo"]</h1>
                    <div class="card-body">
                        <a asp-action="MovieSessions" asp-route-movieId="@ViewBag.id" asp-route-culture="@(ViewData["ctr"].ToString()=="tr-TR" ? "tr-TR":"en-US" )" asp-route-id="@item.CinemaTheater.Id"><h1>@item.CinemaTheater.TheaterNo</h1></a>
                    </div>
                </div>
            </div>


        }
     
        

    </div>
</div>

<!-- TESTIMONIAL =============================-->
<div class="item content" style="visibility:hidden;">
    <div class="container">
        <div class="col-md-10 col-md-offset-1">
            <div class="slide-text">
                <div>
                    <h2><span class="uppercase">Awesome Support</span></h2>
                    <img src="http://wowthemes.net/demo/salique/salique-boxed/images/temp/avatar2.png" alt="Awesome Support">
                    <p>
                        The support... I can only say it's awesome. You make a product and you help people out any way you can even if it means that you have to log in on their dashboard to sort out any problems that customer might have. Simply Outstanding!
                    </p>
                    <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- CALL TO ACTION =============================-->
<section class="content-block" style="background-color:#00bba7;">
    <div class="container text-center">
        <div class="row">
            <div class="col-sm-10 col-sm-offset-1">
                <div class="item" data-scrollreveal="enter top over 0.4s after 0.1s">
                    <h1 class="callactiontitle">
                        @ViewData["PagePromotionCode"] <span class="callactionbutton"><i class="fa fa-gift"></i> WOW24TH</span>
                    </h1>
                </div>
            </div>
        </div>
    </div>
</section>

CinemaSystem/Views/MovieTheatersPage/MovieSessions.cshtml
@{ ViewData["Title"] = "Movie Sessions";
    Layout = "_DefaultLayout";}


<br />
<br />
<br />
<br />

<h2 class="text-center">@ViewData["MovieSessionPageFirstTitle"]</h2>
<br />
<div class="container">
    <div class="row" style="display:flex; justify-content:center; flex-wrap:wrap;">
        @foreach (var item in ViewBag.msbyti)
        {
            <div class="col-md-3 text-center pt-3 pb-4" style="border:3px solid black; margin-left:10px; margin-top:12px; border-radius:10px; padding-bottom:18px;">
                <br />
                <h4>@item.StartedDate</h4>
                <h4>@item.FinishedDate</h4>
                <br />
                <a asp-action="TheaterChairs" asp-route-culture="@(ViewData["ctr"].ToString()=="tr-TR" ? "tr-TR":"en-US" )" asp-controller="MovieTheatersPage" asp-route-id="@item.Id" style="background-color: #00bba7; text-decoration:none; font-size:medium; color:black; padding-right:12px; padding-left:12px; padding-top:6px; padding-bottom:6px; font-weight:700; border-radius:10px;
">@ViewData["MovieSessionPageButton"]</a>

    </div>

}
        @if (ViewBag.msbyti.Count == 0)
        {
            <h3 class="text-center">Seans Bulunmamaktadır</h3>
        }
    </div>
</div>


<!-- TESTIMONIAL =============================-->
<div class="item content" style="visibility:hidden;">
    <div class="container">
        <div class="col-md-10 col-md-offset-1">
            <div class="slide-text">
                <div>
                    <h2><span class="uppercase">Awesome Support</span></h2>
                    <img src="http://wowthemes.net/demo/salique/salique-boxed/images/temp/avatar2.png" alt="Awesome Support">
                    <p>
                        The support... I can only say it's awesome. You make a product and you help people out any way you can even if it means that you have to log in on their dashboard to sort out any problems that customer might have. Simply Outstanding!
                    </p>
                    <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- CALL TO ACTION =============================-->
<section class="content-block" style="background-color:#00bba7;">
    <div class="container text-center">
        <div class="row">
            <div class="col-sm-10 col-sm-offset-1">
                <div class="item" data-scrollreveal="enter top over 0.4s after 0.1s">
                    <h1 class="callactiontitle">
                       @ViewData["PagePromotionCode"] <span class="callactionbutton"><i class="fa fa-gift"></i> WOW24TH</span>
                    </h1>
                </div>
            </div>
        </div>
    </div>
</section>

CinemaSystem/Views/MovieTheatersPage/TheaterChairs.cshtml
@model CinemaSystem.Models.MovieTicket
@using System.Linq;
@using Microsoft.AspNetCore.Identity
@inject SignInManager<Customer> SignInManager
@inject UserManager<Customer> UserManager
@{ ViewData["Title"] = "Theater Chairs";
    Layout = "_DefaultLayout";}

<br />
<br />
<br />
<br />
<div class="container">
    <div class="row">
        @foreach (var item in ViewBag.theaterChairs)
        {

            <div class="col-md-2 text-center pt-3 pb-4" style="border:3px solid black; margin-left:10px; margin-top:12px; border-radius:10px; padding-bottom:18px;">
                <h1 style="@(ViewBag.movieTicketsChair.Contains(item.Id) ? "color:red;":"" )">@item.ChairCode</h1>
            </div>

        }

    </div>
    <br />
    <br />

    <div class="row">
        <div class="col-md-12 d-flex justify-content-center">
            <form asp-action="CreateTicket" asp-controller="MovieTheatersPage">

                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <!-- <label asp-for="MovieSessionId" class="control-label"></label>-->
                    <input asp-for="MovieSessionId" type="hidden" value="@ViewBag.movieSessionId" class="form-control" />
                </div>

                <div class="form-group">
                    <!-- <label asp-for="BuyDate" class="control-label"></label>-->
                    <input asp-for="BuyDate" value="@DateTime.Now" type="hidden" class="form-control" />
                    <span asp-validation-for="BuyDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <!-- <label asp-for="Price" class="control-label"></label>-->
                    <input asp-for="Price" value="50" type="hidden" class="form-control" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <!-- <label asp-for="Number" class="control-label"></label>-->
                    <input asp-for="Number" value="1" type="hidden" class="form-control" />
                    <span asp-validation-for="Number" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <!-- <label asp-for="MovieSessionId" class="control-label"></label>-->
                    <input asp-for="UserId" type="hidden" value="@UserManager.GetUserId(User)" class="form-control" />
                </div>
                @{
                    var avaibleTheaterChair = new List<SelectListItem>();

                    foreach (var item in ViewBag.theaterChairs)
                    {
                        if (!ViewBag.movieTicketsChair.Contains(item.Id))
                        {
                            avaibleTheaterChair.Add(new SelectListItem { Text = item.ChairCode, Value = item.Id.ToString() });
                        }
                    }


                }
                <div class="form-group">
                    <label asp-for="TheaterChairId" class="control-label">@ViewData["TheaterChairsPageChairNo"]</label>
                    <select asp-for="TheaterChairId" class="form-control" asp-items="@avaibleTheaterChair"></select>
                </div>
                <div class="form-group">
                    <input type="submit" value="@ViewData["TheaterChairsPageCreateButton"]" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

</div>